name: connection
description: An opinionated wrapper around the revered http library where HTTP responses are objects for easy parsing and error handling.
version: 0.1.0
repository: https://github.com/0xdir/connection_dart

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0